replicaCount: 1

image:
  repository: <your-docker-hub-username>
  pullPolicy: IfNotPresent

api:
  image: api
  tag: "latest"
  port: 8000

frontend:
  image: frontend
  tag: "latest"
  port: 3000
imagePullSecrets:
  -name: my-dockerhub-secret

service:
  type: LoadBalancer
  apiPort: 8000
  frontendPort: 3000

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  namespace: default
  hosts:
    - host: devops.capstone.com
      paths:
        - path: /api
          pathType: Prefix
          service: api-service
          port: 8000
        - path: /frontend
          pathType: Prefix
          service: frontend-service
          port: 3000

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
