apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: {{ .Release.Name }}-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api
    spec:
      containers:
      - name: api
        image: "{{ .Values.image.repository }}/{{ .Values.api.image }}:{{ .Values.api.tag }}"
        ports:
      - containerPort: {{ .Values.api.port }}
        imagePullSecrets: 
        - name: {{ .Values.imagePullSecrets[0].name }}
