name: CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - 'front-end-nextjs/**'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: SonarQube Analysis
        run: |
          sonar-scanner \
          -Dsonar.projectKey=devops-qr-code \
          -Dsonar.sources=api,front-end-nextjs \
          -Dsonar.host.url=${{ secrets.SONARQUBE_URL }} \
          -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}

      - name: Build and Push API Image
        run: |
          docker build -t your-docker-hub-username/backend:${{ github.sha }} ./api
          docker push your-docker-hub-username/backend:${{ github.sha }}

      - name: Build and Push Frontend Image
        run: |
          docker build -t your-docker-hub-username/frontend:${{ github.sha }} ./front-end-nextjs
          docker push your-docker-hub-username/frontend:${{ github.sha }}

      - name: Trivy Scan for API Image
        run: |
          trivy image your-docker-hub-username/backend:${{ github.sha }}

      - name: Trivy Scan for Frontend Image
        run: |
          trivy image your-docker-hub-username/frontend:${{ github.sha }}

      - name: Update Deployment Manifests
        run: |
          sed -i "s|image: your-docker-hub-username/backend:.*|image: your-docker-hub-username/backend:${{ github.sha }}|" k8s/backend-deployment.yaml
          sed -i "s|image: your-docker-hub-username/frontend:.*|image: your-docker-hub-username/frontend:${{ github.sha }}|" k8s/frontend-deployment.yaml

      - name: Commit and Push Updated Manifests
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add k8s/backend-deployment.yaml k8s/frontend-deployment.yaml
          git commit -m "Update deployment manifests with new image tags"
          git push
