name: CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - 'front-end-nextjs/**'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: SonarQube Analysis
        run: |
          sonar-scanner \
          -Dsonar.projectKey=devops-qr-code \
          -Dsonar.sources=api,front-end-nextjs \
          -Dsonar.host.url=${{ secrets.SONARQUBE_URL }} \
          -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}

      - name: Build and Push API Image
        run: |
          IMAGE_TAG=api-${{ github.sha }}
          docker build -t your-docker-hub-username/backend:$IMAGE_TAG ./api
          docker push your-docker-hub-username/backend:$IMAGE_TAG

      - name: Build and Push Frontend Image
        run: |
          IMAGE_TAG=frontend-${{ github.sha }}
          docker build -t your-docker-hub-username/frontend:$IMAGE_TAG ./front-end-nextjs
          docker push your-docker-hub-username/frontend:$IMAGE_TAG

      - name: Trivy Scan for API Image
        run: |
          trivy image your-docker-hub-username/backend:${{ github.sha }}

      - name: Trivy Scan for Frontend Image
        run: |
          trivy image your-docker-hub-username/frontend:${{ github.sha }}

      - name: Update Values File
        run: |
          sed -i "s|api.image:.*|api.image: your-docker-hub-username/backend:${{ github.sha }}|" k8s/values.yaml
          sed -i "s|frontend.image:.*|frontend.image: your-docker-hub-username/frontend:${{ github.sha }}|" k8s/values.yaml

      - name: Commit and Push Updated Values File
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add k8s/values.yaml
          git commit -m "Update values.yaml with new image tags"
          git push
